### ISSUE TITLE
Playing the Cash Game REQUIRES Bot Farmining

### ISSUE THREAD

**Issue by jztech101** [cracker64/Crackbot#23]
How else are you going to reach 1e+16? And when you do farm, a certain jacob complains the farming is excessive and rate limits it/ban/quiets it. How about we just eliminate farming altogether and create a new mechanic for gaining cash that everyone can/will do without being banned/quieted?

**Comment by jacob1** [comment]
I'm working on making farming so excessively not required. Probably we need some more items between some of the huge gaps around company / country / world. For now, this issue just seems like you are annoyed about your ban :P.

**Comment by io4** [comment]
This was fixed on ebd9ea454601b30ff582b4f20399ba643245715c . ~~@jztech101 please edit your issue to remove your ban compliants. ~~
